### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-webapp#10]
Trying to hack on this at the citation.ccf hackday and it would be great to have a page that shows how to get a dev environment up.  Perhaps imagine you've got a new install of Mac OS X, how would you get coding on a local instance (install brew, install python, install npm, install angular).  Or use having conda installed as a starting point?

**Comment by jameshowison** [comment]
Any luck on this?  Lots that I don't understand in the stack, but would be good to have a "from scratch" in case people want to play with it.

**Comment by hpiwowar** [comment]
Hi James!  Yup, we are going to get good documentation up for stand-alone
desktop/laptop installations, as well as for deploying to heroku.  We
estimate it'll take about a month; that work?  Will keep you posted on
progress.

Heather

--
Heather Piwowar, cofounder
Impactstory <http://impactstory.org/>: We make tools to power the Open
Science revolution
follow at @researchremix <https://twitter.com/researchremix>, @impactstory
<http://twitter.com/impactstory>, and @unpaywall
<https://twitter.com/unpaywall>

**Comment by jameshowison** [comment]
Seems like a conda environment.yml file would be a good approach here?

https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by caseydm** [comment]
Hello. Installation instructions are now available for the [back-end API](https://github.com/Impactstory/citeas-api/blob/master/installation.md) as well as the [front-end web application](https://github.com/Impactstory/citeas-webapp/blob/master/install.md).

I plan to improve the installation process with docker or conda down the road. But this should be a good start for anybody looking to get the app running on their local machine.
