### ISSUE TITLE
Obtain expected results from users

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-webapp#14]
In order to improve over time it would be great to have a from on the results (or error) page that recorded what a user was seeking.  So if someone was "trying it out to see if it found my request for citation." we could learn what they were looking for?  Perhaps something that auto creates an issue on github?

**Comment by caseydm** [comment]
Users can now submit feedback through the 'Results not as expected?' link on the results page and error page. Feedback is sent as an email, which will be turned into a GitHub issue most likely in the main [API repository](https://github.com/Impactstory/citeas-api).
