### ISSUE TITLE
more citation styles

### ISSUE THREAD

**Issue by katrinleinweber** [Impactstory/citeas-webapp#3]
Hello! Besides the [few default styles](https://github.com/Impactstory/citeas-api/commit/60a3daf2df31bd4dcd4267a1493c4675c486f763#diff-30d35786cfd776b1f92066d4c51b3c36R80) will it be possible to use more or even any that are on https://www.zotero.org/styles or https://github.com/citation-style-language/styles?

**Comment by hpiwowar** [comment]
Thanks for the request!  

It'd be easy to add in a few if you have favourites we are missing!  Let me know the filenames from https://github.com/citation-style-language/styles

It's harder to made it handle any arbitrary one from the list.  Are you building something that would need that?

**Comment by katrinleinweber** [comment]
Sorry, about #2. I was on a bad connection and updating that accidental submit with the above text didn't work.

No, I'm not building anything on top of CiteAs, just noticed that the list of style options was limited and hard-coded. Would it be useful to your project to expediently add a few more styles? I imagine that a user would instead appreciate a search box to quickly find the style they want. That search box could feed off [styles](https://github.com/citation-style-language/styles). Additionally maybe even with fuzzy-matching.

**Comment by hpiwowar** [comment]
Thanks!  Yeah, agreed it would be cool to get any style.  It makes it the apps built on the API a bit slower though, because there are too many formats to return all the results in the API for all the citation formats, so the app would have to call the API with the specific format once the user picked it from the drop down.  

We've opted to go with the short-list for now, but are definitely interested in hearing from anyone who needs it to work differently!

**Comment by katrinleinweber** [comment]
Yeah, that doesn't scale... Thanks for explaining :-)

Is it a longer-term goal to avoid duplicating the citation data in the JSON dataset that your API returns, and do the style-based rendering citation in the user's browser?

**Comment by hpiwowar** [comment]
Sorry for the slow response.  I can see reasons why that might be good in
some ways but no, that isn't a goal at the moment :)
Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by katrinleinweber** [comment]
OK, FYI only then: Zenodo [has](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/templates/zenodo_records/box/share.html#L36) [something](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/theme/static/scss/record.scss#L132) [similar](https://github.com/zenodo/zenodo/tree/master/zenodo/modules/records/templates/zenodo_records/record_detail.html#L121) ("Invenio CSL"). Not sure where they are fetching the styles from, though.
