### ISSUE TITLE
Link DOI API response to description of returned metadata

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-webapp#7]
Could we change the link given for "Looking in the user input, we found a DOI.
DOI API response" from "what is a DOI" to https://project-thor.readme.io/docs/accessing-doi-metadata which describes how one can get metadata for any given DOI.

That was new to me, and I think, a good education opportunity?

**Comment by hpiwowar** [comment]
Good idea!  Leaving the "what is a DOI" but added this link as well:
![image](https://user-images.githubusercontent.com/223105/38959379-4a074644-4315-11e8-9431-1afb3c38da7d.png)
